### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [ACBSmith/george-bernard-shaw_man-and-superman#1]
Dedication:
- [x] Fix semantics for the dedication. It is not a chapter.

- [x] Remove `text-indent="0"`.

- [ ] Wrap the salutation in a `<header>`, like a letter.

- [x] Wrap the sender and dateline in a `<footer>`, like a letter.

Dramatis Personae:
- [x] Fix the semantics for the dramatis personae. The `<body>` should look like this:
`<body epub:type="frontmatter z3998:fiction z3998:drama">`

Appendix 1:
- [x] Fix the semantics for Appendix 1. It is backmatter and an appendix.

- [x] Wrap the signature in a `<footer>` (located in Foreward).

- [x] You need to use levels `<h4>` and `<h5>` for the chapters.

Appendix 2:
- [x] Fix the semantics for Appendix 2. It is backmatter and an appendix.

- [x] Alex: "<article> is not correct anywhere in this kind of book." Convert the `<article>`s into `<section>`s.

Content.opf:
- [x] Reorder `<spine>`. You will also have to reorder the ToC. Make sure to add the List of Illustrations before you make these changes.

Misc. Issues:
- [x] Since your production contains images you must have a List of Illustrations file. See the manual on everything related to that.

**Comment by ACBSmith** [comment]
> Wrap the salutation in a <header>, like a letter.

I’m excluding it because of 7.7.2.2: If there is only a salutation and no other header content, the <header> element is omitted.

**Comment by EmmaSweeney** [comment]
- [x] The dedication should have `epub:type="dedication"`.

- [x] Lint is showing new errors.

**Comment by ACBSmith** [comment]
> Lint is showing new errors.

- I'm assuming that the author is also the illustrator - I made the vectorisation, but he presumably wrote the music
- Lint is complaining about "Internal link beginning with ../text/." but that's the format in the example in 7.9.6; on top of that, the links work.

**Comment by EmmaSweeney** [comment]
Lint is correct. You need to remove "../text/". 

Make the link match the one in the manual section "XHTML formatting" ([section 1.1.2](https://standardebooks.org/manual/1.4.0/single-page#1.1.2))

**Comment by ACBSmith** [comment]
Should I put in a PR for the example in 7.9.6 to remove the "../text/" from that line?

**Comment by EmmaSweeney** [comment]
I would mention it in the google chat. Alex may make the changes himself or have you send a PR.

**Comment by EmmaSweeney** [comment]
OK, all of theses issues are fixed so I will close this thread. It will take me a day or two to finish reviewing (plays take awhile to review), and if I find more issues, I will start a new issue thread.

**Comment by ACBSmith** [comment]
Cheers! Don't stress about it - I have an inkling that I might want to do Hedda Gabler next, and so I have plenty of work cut out for me looking for PD art of a woman with a pistol.
