### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [ACBSmith/george-bernard-shaw_man-and-superman#2]
local.css:
- [x] Remove unused CSS:
```
[epub|type~="z3998:dramatis-personae"] ul + p{
	margin-top: 2em;
}
```

- [x] You are missing CSS for images ([section 7.8](https://standardebooks.org/manual/1.4.0/single-page#7.8)).

- [x] You need to add the styling `text-indent: 0;` to `#appendix-1 p b{ }`.

Act 1:

- [x] Remove `<!--division of paragraph-->`.

- [x] Below `<!--division of paragraph-->`, there is a stage direction in the middle of the dialogue. You can split this into 3 different `<tr>` sections:
```
<tr>
	<td epub:type="z3998:persona">Ramsden</td>
	<td>I am sorry, Annie...</td>
</tr>
<tr>
	<td/>
	<td>
		<i epub:type="z3998:stage-direction"><b epub:type="z3998:persona">Ann</b> assents...</i>
	</td>
</tr>
<tr>
	<td/>
	<td>I must say I am surprised...</td>
```
Note: You don't need the persona for the second section of dialogue. This will add space around the stage direction and make it match the rest of the play.

Modernize Spelling:
- [x] Run `se modernize-spelling .` to convert Mahomet to Muhammad.

Image Titles:
- [x] The image title that contains a fraction. It must follow the typography standards ([section 8.8.5.2](https://standardebooks.org/manual/1.4.0/8-typography#8.8.5.2)).

Image Files:
- [x] You have duplicate SVG files. Just the XML music files should be located in the images file that contains the cover.jpg and cover.source.jpg, while the SVGs should be located in george-bernard-shaw_man-and-superman/src/epub/images.

Branches:
- [x] Since you no longer need the other repository branch you can delete it.

Building Errors:
- [x] After running `se build --output-dir=$HOME/dist/ --kindle --kobo --check .` two errors pop up. Theses need to be fixed.

**Comment by ACBSmith** [comment]
For image CSS, am I correct in assuming I should also use the inline block?
```
figure{
	margin: 1em auto;
	text-align: center;
}
```

**Comment by EmmaSweeney** [comment]
I believe so.

**Comment by ACBSmith** [comment]
Then I believe I've addressed all these, and I'll close the thread.

**Comment by EmmaSweeney** [comment]
You need to tweak the CSS in Appendix 1. The Foreword header appears on a separate page from the text. These need to appear on the same page. Try a more specific selector.

**Comment by ACBSmith** [comment]
I’m struggling to replicate the kindle image issue - the azw3 is looking good on my end. Can you give me more info about your setup?

**Comment by ACBSmith** [comment]
I've reworked the CSS so that the children are no longer tagged by that, and it's looking correct to me when I build it

**Comment by ACBSmith** [comment]
Interesting - I've tried opening the azw3 with my kindle app on my mac, and it's crashing the app. I wonder if that's the images?

**Comment by EmmaSweeney** [comment]
I'm opening the AZW3 file with Calibre. This is what I see.

![2021-03-10-175944_1920x1080_scrot](https://user-images.githubusercontent.com/56360562/110709724-a8c82d00-81ca-11eb-9692-b859d5cf923e.png)

**Comment by ACBSmith** [comment]
This is what it looks like within my calibre reader. My kindle has decided to be stuck on USB drive mode, and so I can’t load it onto that to test it.

**Comment by ACBSmith** [comment]
<img width="1440" alt="Screenshot 2021-01-16 at 22 08 42" src="https://user-images.githubusercontent.com/19839288/110713187-623df700-81f9-11eb-9d06-d7aef81bd51d.png">

**Comment by ACBSmith** [comment]
<img width="655" alt="Screenshot 2021-03-10 at 23 03 33" src="https://user-images.githubusercontent.com/19839288/110713234-7bdf3e80-81f9-11eb-8edd-31f4ba216d56.png">

**Comment by ACBSmith** [comment]
In fact, when I was able to upload it to my kindle, it worked for me.

![P_20210310_234438_vHDR_Auto](https://user-images.githubusercontent.com/19839288/110714108-e80e7200-81fa-11eb-99cc-e30406d2c36e.jpg)
![P_20210310_234454_vHDR_Auto](https://user-images.githubusercontent.com/19839288/110714110-e93f9f00-81fa-11eb-85d3-2cc962ac1959.jpg)
![P_20210310_234432_vHDR_Auto](https://user-images.githubusercontent.com/19839288/110714101-e2b12780-81fa-11eb-8fb9-b928dab220ad.jpg)

**Comment by ACBSmith** [comment]
One last thing: I found an error in the appendix-2 CSS, so I've changed it to this:

```
#appendix-2 h2{
	break-after: page;
}

#appendix-2 header{
	break-after: avoid;
}
```
